--------------------------------------------------------
--  File created - Friday-August-07-2015   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence HAK_AKSES_SEQ
-- Saya mencoba edit ini
--------------------------------------------------------

   CREATE SEQUENCE  "PREPLANNING"."HAK_AKSES_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence LOKASI_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PREPLANNING"."LOKASI_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence MEETING_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PREPLANNING"."MEETING_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence MEMBERUSER_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PREPLANNING"."MEMBERUSER_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_CATEGORY_ID
--------------------------------------------------------

   CREATE SEQUENCE  "PREPLANNING"."SEQ_CATEGORY_ID"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_USER_ID
--------------------------------------------------------

   CREATE SEQUENCE  "PREPLANNING"."SEQ_USER_ID"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SUB_LOKASI_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PREPLANNING"."SUB_LOKASI_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence TRANSAKSI_DETAIL2_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PREPLANNING"."TRANSAKSI_DETAIL2_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence TRANSAKSI_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PREPLANNING"."TRANSAKSI_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table HAK_AKSES
--------------------------------------------------------

  CREATE TABLE "PREPLANNING"."HAK_AKSES" 
   (	"ID_HAK_AKSES" NUMBER(11,0), 
	"ID_USER" NUMBER(11,0), 
	"ID_LOKASI" NUMBER(11,0), 
	"HAK_AKSES" VARCHAR2(30 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table LOKASI
--------------------------------------------------------

  CREATE TABLE "PREPLANNING"."LOKASI" 
   (	"ID_LOKASI" NUMBER(11,0), 
	"NAMA_LOKASI" VARCHAR2(50 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table MEETING
--------------------------------------------------------

  CREATE TABLE "PREPLANNING"."MEETING" 
   (	"ID_MEETING" NUMBER(11,0), 
	"JUDUL_RAPAT" VARCHAR2(100 BYTE), 
	"TANGGAL" DATE, 
	"WAKTU" VARCHAR2(30 BYTE), 
	"TEMPAT" VARCHAR2(50 BYTE), 
	"DISETUJUI" VARCHAR2(50 BYTE), 
	"DICATAT" VARCHAR2(50 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table MEMBER
--------------------------------------------------------

  CREATE TABLE "PREPLANNING"."MEMBER" 
   (	"ID_USER" NUMBER(11,0), 
	"USERNAME" VARCHAR2(50 BYTE), 
	"PASSWORD" VARCHAR2(45 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SUB_LOKASI
--------------------------------------------------------

  CREATE TABLE "PREPLANNING"."SUB_LOKASI" 
   (	"ID_SUB_LOKASI" NUMBER(11,0), 
	"ID_LOKASI" NUMBER(11,0), 
	"NAMA_SUB_LOKASI" VARCHAR2(50 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TRANSAKSI
--------------------------------------------------------

  CREATE TABLE "PREPLANNING"."TRANSAKSI" 
   (	"ID_TRANSAKSI" NUMBER(11,0), 
	"ID_MEETING" NUMBER(11,0), 
	"ID_LOKASI" NUMBER(11,0), 
	"ID_SUB_LOKASI" NUMBER(11,0), 
	"ID_USER" NUMBER(11,0), 
	"WR_WO" VARCHAR2(40 BYTE), 
	"NOTE" VARCHAR2(4000 BYTE), 
	"STATUS" VARCHAR2(100 BYTE), 
	"ATTACHMENT" BLOB, 
	"TARGET" VARCHAR2(300 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" 
 LOB ("ATTACHMENT") STORE AS (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 PCTVERSION 10
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table TRANSAKSI_DETAIL
--------------------------------------------------------

  CREATE TABLE "PREPLANNING"."TRANSAKSI_DETAIL" 
   (	"ID_TRANSAKSI_DETAIL" NUMBER(11,0), 
	"ID_TRANSAKSI" NUMBER(11,0), 
	"ID_LOKASI" NUMBER(11,0), 
	"ID_SUB_LOKASI" NUMBER(11,0), 
	"NOTE" VARCHAR2(4000 BYTE), 
	"STATUS" VARCHAR2(100 BYTE), 
	"ATTACHMENT" BLOB
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" 
 LOB ("ATTACHMENT") STORE AS (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 PCTVERSION 10
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)) ;
REM INSERTING into PREPLANNING.HAK_AKSES
SET DEFINE OFF;
REM INSERTING into PREPLANNING.LOKASI
SET DEFINE OFF;
REM INSERTING into PREPLANNING.MEETING
SET DEFINE OFF;
REM INSERTING into PREPLANNING.MEMBER
SET DEFINE OFF;
REM INSERTING into PREPLANNING.SUB_LOKASI
SET DEFINE OFF;
REM INSERTING into PREPLANNING.TRANSAKSI
SET DEFINE OFF;
REM INSERTING into PREPLANNING.TRANSAKSI_DETAIL
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index HAK_AKSES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PREPLANNING"."HAK_AKSES_PK" ON "PREPLANNING"."HAK_AKSES" ("ID_HAK_AKSES") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TRANSAKSI_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PREPLANNING"."TRANSAKSI_PK" ON "PREPLANNING"."TRANSAKSI" ("ID_TRANSAKSI") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index MEETING_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PREPLANNING"."MEETING_PK" ON "PREPLANNING"."MEETING" ("ID_MEETING") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index MEMBER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PREPLANNING"."MEMBER_PK" ON "PREPLANNING"."MEMBER" ("ID_USER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TRANSAKSI_DETAIL_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PREPLANNING"."TRANSAKSI_DETAIL_PK" ON "PREPLANNING"."TRANSAKSI_DETAIL" ("ID_TRANSAKSI_DETAIL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SUB_LOKASI_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PREPLANNING"."SUB_LOKASI_PK" ON "PREPLANNING"."SUB_LOKASI" ("ID_SUB_LOKASI") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index LOKASI_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PREPLANNING"."LOKASI_PK" ON "PREPLANNING"."LOKASI" ("ID_LOKASI") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table MEETING
--------------------------------------------------------

  ALTER TABLE "PREPLANNING"."MEETING" ADD CONSTRAINT "MEETING_PK" PRIMARY KEY ("ID_MEETING")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "PREPLANNING"."MEETING" MODIFY ("ID_MEETING" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table HAK_AKSES
--------------------------------------------------------

  ALTER TABLE "PREPLANNING"."HAK_AKSES" ADD CONSTRAINT "HAK_AKSES_PK" PRIMARY KEY ("ID_HAK_AKSES")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "PREPLANNING"."HAK_AKSES" MODIFY ("ID_HAK_AKSES" NOT NULL ENABLE);
 
  ALTER TABLE "PREPLANNING"."HAK_AKSES" MODIFY ("ID_USER" NOT NULL ENABLE);
 
  ALTER TABLE "PREPLANNING"."HAK_AKSES" MODIFY ("ID_LOKASI" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MEMBER
--------------------------------------------------------

  ALTER TABLE "PREPLANNING"."MEMBER" ADD CONSTRAINT "MEMBER_PK" PRIMARY KEY ("ID_USER")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "PREPLANNING"."MEMBER" MODIFY ("ID_USER" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TRANSAKSI_DETAIL
--------------------------------------------------------

  ALTER TABLE "PREPLANNING"."TRANSAKSI_DETAIL" MODIFY ("ID_TRANSAKSI_DETAIL" NOT NULL ENABLE);
 
  ALTER TABLE "PREPLANNING"."TRANSAKSI_DETAIL" MODIFY ("ID_TRANSAKSI" NOT NULL ENABLE);
 
  ALTER TABLE "PREPLANNING"."TRANSAKSI_DETAIL" ADD CONSTRAINT "TRANSAKSI_DETAIL_PK" PRIMARY KEY ("ID_TRANSAKSI_DETAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SUB_LOKASI
--------------------------------------------------------

  ALTER TABLE "PREPLANNING"."SUB_LOKASI" ADD CONSTRAINT "SUB_LOKASI_PK" PRIMARY KEY ("ID_SUB_LOKASI")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "PREPLANNING"."SUB_LOKASI" MODIFY ("ID_SUB_LOKASI" NOT NULL ENABLE);
 
  ALTER TABLE "PREPLANNING"."SUB_LOKASI" MODIFY ("ID_LOKASI" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table LOKASI
--------------------------------------------------------

  ALTER TABLE "PREPLANNING"."LOKASI" ADD CONSTRAINT "LOKASI_PK" PRIMARY KEY ("ID_LOKASI")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "PREPLANNING"."LOKASI" MODIFY ("ID_LOKASI" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TRANSAKSI
--------------------------------------------------------

  ALTER TABLE "PREPLANNING"."TRANSAKSI" MODIFY ("ID_TRANSAKSI" NOT NULL ENABLE);
 
  ALTER TABLE "PREPLANNING"."TRANSAKSI" MODIFY ("ID_MEETING" NOT NULL ENABLE);
 
  ALTER TABLE "PREPLANNING"."TRANSAKSI" MODIFY ("ID_LOKASI" NOT NULL ENABLE);
 
  ALTER TABLE "PREPLANNING"."TRANSAKSI" MODIFY ("ID_USER" NOT NULL ENABLE);
 
  ALTER TABLE "PREPLANNING"."TRANSAKSI" ADD CONSTRAINT "TRANSAKSI_PK" PRIMARY KEY ("ID_TRANSAKSI")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table HAK_AKSES
--------------------------------------------------------

  ALTER TABLE "PREPLANNING"."HAK_AKSES" ADD CONSTRAINT "HAK_AKSES_FK" FOREIGN KEY ("ID_USER")
	  REFERENCES "PREPLANNING"."MEMBER" ("ID_USER") ENABLE;
 
  ALTER TABLE "PREPLANNING"."HAK_AKSES" ADD CONSTRAINT "HAK_AKSES_FK2" FOREIGN KEY ("ID_LOKASI")
	  REFERENCES "PREPLANNING"."LOKASI" ("ID_LOKASI") ENABLE;



--------------------------------------------------------
--  Ref Constraints for Table SUB_LOKASI
--------------------------------------------------------

  ALTER TABLE "PREPLANNING"."SUB_LOKASI" ADD CONSTRAINT "SUB_LOKASI_FK" FOREIGN KEY ("ID_LOKASI")
	  REFERENCES "PREPLANNING"."LOKASI" ("ID_LOKASI") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TRANSAKSI
--------------------------------------------------------

  ALTER TABLE "PREPLANNING"."TRANSAKSI" ADD CONSTRAINT "TRANSAKSI_FK" FOREIGN KEY ("ID_MEETING")
	  REFERENCES "PREPLANNING"."MEETING" ("ID_MEETING") ENABLE;
 
  ALTER TABLE "PREPLANNING"."TRANSAKSI" ADD CONSTRAINT "TRANSAKSI_FK2" FOREIGN KEY ("ID_LOKASI")
	  REFERENCES "PREPLANNING"."LOKASI" ("ID_LOKASI") ENABLE;
 
  ALTER TABLE "PREPLANNING"."TRANSAKSI" ADD CONSTRAINT "TRANSAKSI_FK3" FOREIGN KEY ("ID_SUB_LOKASI")
	  REFERENCES "PREPLANNING"."SUB_LOKASI" ("ID_SUB_LOKASI") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TRANSAKSI_DETAIL
--------------------------------------------------------

  ALTER TABLE "PREPLANNING"."TRANSAKSI_DETAIL" ADD CONSTRAINT "TRANSAKSI_DETAIL_FK" FOREIGN KEY ("ID_TRANSAKSI")
	  REFERENCES "PREPLANNING"."TRANSAKSI" ("ID_TRANSAKSI") ENABLE;
--------------------------------------------------------
--  DDL for Trigger BI_HAK_AKSES
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "PREPLANNING"."BI_HAK_AKSES" 
  before insert on "HAK_AKSES"               
  for each row  
begin   
    select "HAK_AKSES_SEQ".nextval into :NEW.ID_HAK_AKSES from dual; 
end; 

/
ALTER TRIGGER "PREPLANNING"."BI_HAK_AKSES" ENABLE;
--------------------------------------------------------
--  DDL for Trigger BI_LOKASI
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "PREPLANNING"."BI_LOKASI" 
  before insert on "LOKASI"               
  for each row  
begin   
    select "LOKASI_SEQ".nextval into :NEW.ID_LOKASI from dual; 
end; 

/
ALTER TRIGGER "PREPLANNING"."BI_LOKASI" ENABLE;
--------------------------------------------------------
--  DDL for Trigger BI_MEETING
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "PREPLANNING"."BI_MEETING" 
  before insert on "MEETING"               
  for each row  
begin   
    select "MEETING_SEQ".nextval into :NEW.ID_MEETING from dual; 
end; 

/
ALTER TRIGGER "PREPLANNING"."BI_MEETING" ENABLE;
--------------------------------------------------------
--  DDL for Trigger BI_MEMBER
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "PREPLANNING"."BI_MEMBER" 
  before insert on "MEMBER"               
  for each row  
begin   
    select "MEMBERUSER_SEQ".nextval into :NEW.ID_USER from dual; 
end; 

/
ALTER TRIGGER "PREPLANNING"."BI_MEMBER" ENABLE;
--------------------------------------------------------
--  DDL for Trigger BI_SUB_LOKASI
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "PREPLANNING"."BI_SUB_LOKASI" 
  before insert on "SUB_LOKASI"               
  for each row  
begin   
    select "SUB_LOKASI_SEQ".nextval into :NEW.ID_SUB_LOKASI from dual; 
end; 

/
ALTER TRIGGER "PREPLANNING"."BI_SUB_LOKASI" ENABLE;
--------------------------------------------------------
--  DDL for Trigger BI_TRANSAKSI
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "PREPLANNING"."BI_TRANSAKSI" 
  before insert on "TRANSAKSI"               
  for each row  
begin   
    select "TRANSAKSI_SEQ".nextval into :NEW.ID_TRANSAKSI from dual; 
end; 

/
ALTER TRIGGER "PREPLANNING"."BI_TRANSAKSI" ENABLE;
--------------------------------------------------------
--  DDL for Trigger BI_TRANSAKSI_DETAIL
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "PREPLANNING"."BI_TRANSAKSI_DETAIL" 
  before insert on "TRANSAKSI_DETAIL"               
  for each row  
begin   
    select "TRANSAKSI_DETAIL2_SEQ".nextval into :NEW.ID_TRANSAKSI_DETAIL from dual; 
end; 

/
ALTER TRIGGER "PREPLANNING"."BI_TRANSAKSI_DETAIL" ENABLE;
